// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppContext represents the main application context
 * It implements the ServiceStartup interface for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bindings$0 from "../bindings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../events/models.js";

/**
 * GetEvents returns the event manager (for setup from main.go)
 */
export function GetEvents(): $CancellablePromise<events$0.EventManager | null> {
    return $Call.ByID(3928269168).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Maps returns the map service binding
 */
export function Maps(): $CancellablePromise<bindings$0.MapBinding | null> {
    return $Call.ByID(136851508).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Nodes returns the node service binding
 */
export function Nodes(): $CancellablePromise<bindings$0.NodeBinding | null> {
    return $Call.ByID(497130324).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Thinking returns the thinking service binding
 */
export function Thinking(): $CancellablePromise<bindings$0.ThinkingBinding | null> {
    return $Call.ByID(3474810775).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = events$0.EventManager.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = bindings$0.MapBinding.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = bindings$0.NodeBinding.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = bindings$0.ThinkingBinding.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
