/**
 * Wails Runtime Index
 * Exports all Wails-specific functionality
 */

export * from './ipc';
export * from './events';

// Re-export Wails runtime types (will be generated by Wails)
// export * from '../../wailsjs/runtime/runtime';

// Placeholder for Wails runtime - will be replaced by actual Wails bindings
export interface WailsRuntime {
  EventsOn: (event: string, callback: (data: any) => void) => void;
  EventsOff: (event: string) => void;
  EventsEmit: (event: string, ...args: any[]) => void;
}
