// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigBinding exposes config operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLLMConfig returns the current LLM configuration
 */
export function GetLLMConfig(): $CancellablePromise<$models.LLMConfigResponse> {
    return $Call.ByID(2247994523).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveLLMConfig saves the LLM configuration
 */
export function SaveLLMConfig(req: $models.SaveLLMConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(2843876480, req);
}

/**
 * TestLLMConfig tests the LLM configuration by making a simple API call
 */
export function TestLLMConfig(req: $models.SaveLLMConfigRequest): $CancellablePromise<string> {
    return $Call.ByID(1969882335, req);
}

// Private type creation functions
const $$createType0 = $models.LLMConfigResponse.createFrom;
