// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MapBinding exposes map operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateMap creates a new thinking map
 */
export function CreateMap(req: $models.CreateMapRequest): $CancellablePromise<$models.MapResponse> {
    return $Call.ByID(305994242, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteMap deletes a thinking map
 */
export function DeleteMap(mapID: string): $CancellablePromise<void> {
    return $Call.ByID(856772275, mapID);
}

/**
 * GetMap retrieves a specific thinking map
 */
export function GetMap(mapID: string): $CancellablePromise<$models.MapResponse> {
    return $Call.ByID(2436971178, mapID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListMaps retrieves a list of thinking maps
 */
export function ListMaps(query: $models.MapListQuery): $CancellablePromise<$models.MapListResponse> {
    return $Call.ByID(2968624063, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateMap updates a thinking map
 */
export function UpdateMap(mapID: string, req: $models.UpdateMapRequest): $CancellablePromise<$models.MapResponse> {
    return $Call.ByID(982050677, mapID, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MapResponse.createFrom;
const $$createType1 = $models.MapListResponse.createFrom;
