// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * ConclusionRequest represents a request for conclusion
 */
export class ConclusionRequest {
    "nodeId": string;
    "reference": string;
    "instruction": string;

    /** Creates a new ConclusionRequest instance. */
    constructor($$source: Partial<ConclusionRequest> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("reference" in $$source)) {
            this["reference"] = "";
        }
        if (!("instruction" in $$source)) {
            this["instruction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConclusionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ConclusionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConclusionRequest($$parsedSource as Partial<ConclusionRequest>);
    }
}

/**
 * CreateMapRequest represents a request to create a map
 */
export class CreateMapRequest {
    "title": string;
    "problem": string;
    "problemType": string;
    "target": string;
    "keyPoints": string[];
    "constraints": string[];

    /** Creates a new CreateMapRequest instance. */
    constructor($$source: Partial<CreateMapRequest> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("problem" in $$source)) {
            this["problem"] = "";
        }
        if (!("problemType" in $$source)) {
            this["problemType"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("keyPoints" in $$source)) {
            this["keyPoints"] = [];
        }
        if (!("constraints" in $$source)) {
            this["constraints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateMapRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateMapRequest {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyPoints" in $$parsedSource) {
            $$parsedSource["keyPoints"] = $$createField4_0($$parsedSource["keyPoints"]);
        }
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField5_0($$parsedSource["constraints"]);
        }
        return new CreateMapRequest($$parsedSource as Partial<CreateMapRequest>);
    }
}

/**
 * CreateNodeRequest represents a request to create a node
 */
export class CreateNodeRequest {
    "parentId": string;
    "nodeType": string;
    "question": string;
    "target": string;
    "position": models$0.Position;

    /** Creates a new CreateNodeRequest instance. */
    constructor($$source: Partial<CreateNodeRequest> = {}) {
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("nodeType" in $$source)) {
            this["nodeType"] = "";
        }
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = (new models$0.Position());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateNodeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateNodeRequest {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField4_0($$parsedSource["position"]);
        }
        return new CreateNodeRequest($$parsedSource as Partial<CreateNodeRequest>);
    }
}

/**
 * DecompositionRequest represents a request for decomposition
 */
export class DecompositionRequest {
    "nodeId": string;
    "clarification": string;
    "isDecomposed": boolean;

    /** Creates a new DecompositionRequest instance. */
    constructor($$source: Partial<DecompositionRequest> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("clarification" in $$source)) {
            this["clarification"] = "";
        }
        if (!("isDecomposed" in $$source)) {
            this["isDecomposed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecompositionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DecompositionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DecompositionRequest($$parsedSource as Partial<DecompositionRequest>);
    }
}

/**
 * ExecutableNodesResponse represents executable nodes
 */
export class ExecutableNodesResponse {
    "nodeIds": string[];
    "suggestedNodeId": string;

    /** Creates a new ExecutableNodesResponse instance. */
    constructor($$source: Partial<ExecutableNodesResponse> = {}) {
        if (!("nodeIds" in $$source)) {
            this["nodeIds"] = [];
        }
        if (!("suggestedNodeId" in $$source)) {
            this["suggestedNodeId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutableNodesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutableNodesResponse {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodeIds" in $$parsedSource) {
            $$parsedSource["nodeIds"] = $$createField0_0($$parsedSource["nodeIds"]);
        }
        return new ExecutableNodesResponse($$parsedSource as Partial<ExecutableNodesResponse>);
    }
}

/**
 * LLMConfigResponse is the response for LLM config (api_key is masked)
 */
export class LLMConfigResponse {
    "base_url": string;
    "api_key": string;
    "model": string;

    /** Creates a new LLMConfigResponse instance. */
    constructor($$source: Partial<LLMConfigResponse> = {}) {
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfigResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMConfigResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfigResponse($$parsedSource as Partial<LLMConfigResponse>);
    }
}

/**
 * MapBinding exposes map operations to the frontend
 */
export class MapBinding {

    /** Creates a new MapBinding instance. */
    constructor($$source: Partial<MapBinding> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): MapBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MapBinding($$parsedSource as Partial<MapBinding>);
    }
}

/**
 * MapListQuery represents query parameters for listing maps
 */
export class MapListQuery {
    "page": number;
    "limit": number;
    "status"?: number;
    "problemType"?: string;
    "search"?: string;
    "dateRange"?: string;

    /** Creates a new MapListQuery instance. */
    constructor($$source: Partial<MapListQuery> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapListQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): MapListQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MapListQuery($$parsedSource as Partial<MapListQuery>);
    }
}

/**
 * MapListResponse represents a paginated list of maps
 */
export class MapListResponse {
    "total": number;
    "page": number;
    "limit": number;
    "items": MapResponse[];

    /** Creates a new MapListResponse instance. */
    constructor($$source: Partial<MapListResponse> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapListResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MapListResponse {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        return new MapListResponse($$parsedSource as Partial<MapListResponse>);
    }
}

/**
 * MapResponse represents a map in API responses
 */
export class MapResponse {
    "id": string;
    "title": string;
    "problem": string;
    "problemType": string;
    "target": string;
    "keyPoints": string[];
    "constraints": string[];
    "conclusion": string;
    "status": string;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new MapResponse instance. */
    constructor($$source: Partial<MapResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("problem" in $$source)) {
            this["problem"] = "";
        }
        if (!("problemType" in $$source)) {
            this["problemType"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("keyPoints" in $$source)) {
            this["keyPoints"] = [];
        }
        if (!("constraints" in $$source)) {
            this["constraints"] = [];
        }
        if (!("conclusion" in $$source)) {
            this["conclusion"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MapResponse {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyPoints" in $$parsedSource) {
            $$parsedSource["keyPoints"] = $$createField5_0($$parsedSource["keyPoints"]);
        }
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField6_0($$parsedSource["constraints"]);
        }
        return new MapResponse($$parsedSource as Partial<MapResponse>);
    }
}

/**
 * NodeBinding exposes node operations to the frontend
 */
export class NodeBinding {

    /** Creates a new NodeBinding instance. */
    constructor($$source: Partial<NodeBinding> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeBinding($$parsedSource as Partial<NodeBinding>);
    }
}

/**
 * NodeResponse represents a node in API responses
 */
export class NodeResponse {
    "id": string;
    "mapId": string;
    "parentId": string;
    "nodeType": string;
    "question": string;
    "target": string;
    "context": models$0.DependentContext;
    "decomposition": models$0.Decomposition;
    "conclusion": models$0.Conclusion;
    "status": string;
    "position": models$0.Position;
    "dependencies": string[];
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new NodeResponse instance. */
    constructor($$source: Partial<NodeResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("mapId" in $$source)) {
            this["mapId"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("nodeType" in $$source)) {
            this["nodeType"] = "";
        }
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = (new models$0.DependentContext());
        }
        if (!("decomposition" in $$source)) {
            this["decomposition"] = (new models$0.Decomposition());
        }
        if (!("conclusion" in $$source)) {
            this["conclusion"] = (new models$0.Conclusion());
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = (new models$0.Position());
        }
        if (!("dependencies" in $$source)) {
            this["dependencies"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeResponse {
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType6;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField6_0($$parsedSource["context"]);
        }
        if ("decomposition" in $$parsedSource) {
            $$parsedSource["decomposition"] = $$createField7_0($$parsedSource["decomposition"]);
        }
        if ("conclusion" in $$parsedSource) {
            $$parsedSource["conclusion"] = $$createField8_0($$parsedSource["conclusion"]);
        }
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField10_0($$parsedSource["position"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField11_0($$parsedSource["dependencies"]);
        }
        return new NodeResponse($$parsedSource as Partial<NodeResponse>);
    }
}

/**
 * SaveLLMConfigRequest is the request to save LLM config
 */
export class SaveLLMConfigRequest {
    "base_url": string;
    "api_key": string;
    "model": string;

    /** Creates a new SaveLLMConfigRequest instance. */
    constructor($$source: Partial<SaveLLMConfigRequest> = {}) {
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveLLMConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveLLMConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveLLMConfigRequest($$parsedSource as Partial<SaveLLMConfigRequest>);
    }
}

/**
 * ThinkingBinding exposes AI thinking operations to the frontend
 */
export class ThinkingBinding {

    /** Creates a new ThinkingBinding instance. */
    constructor($$source: Partial<ThinkingBinding> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThinkingBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): ThinkingBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThinkingBinding($$parsedSource as Partial<ThinkingBinding>);
    }
}

/**
 * UnderstandingRequest represents a request for understanding
 */
export class UnderstandingRequest {
    "nodeId": string;
    "query": string;

    /** Creates a new UnderstandingRequest instance. */
    constructor($$source: Partial<UnderstandingRequest> = {}) {
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnderstandingRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UnderstandingRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnderstandingRequest($$parsedSource as Partial<UnderstandingRequest>);
    }
}

/**
 * UpdateMapRequest represents a request to update a map
 */
export class UpdateMapRequest {
    "status"?: number;
    "problem"?: string;
    "problemType"?: string;
    "target"?: string;
    "keyPoints"?: string[];
    "constraints"?: string[];
    "conclusion"?: string;

    /** Creates a new UpdateMapRequest instance. */
    constructor($$source: Partial<UpdateMapRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateMapRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateMapRequest {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyPoints" in $$parsedSource) {
            $$parsedSource["keyPoints"] = $$createField4_0($$parsedSource["keyPoints"]);
        }
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField5_0($$parsedSource["constraints"]);
        }
        return new UpdateMapRequest($$parsedSource as Partial<UpdateMapRequest>);
    }
}

/**
 * UpdateNodeRequest represents a request to update a node
 */
export class UpdateNodeRequest {
    "question"?: string;
    "target"?: string;
    "position"?: models$0.Position;
    "status"?: string;

    /** Creates a new UpdateNodeRequest instance. */
    constructor($$source: Partial<UpdateNodeRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateNodeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateNodeRequest {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField2_0($$parsedSource["position"]);
        }
        return new UpdateNodeRequest($$parsedSource as Partial<UpdateNodeRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.Position.createFrom;
const $$createType2 = MapResponse.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.DependentContext.createFrom;
const $$createType5 = models$0.Decomposition.createFrom;
const $$createType6 = models$0.Conclusion.createFrom;
