// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NodeBinding exposes node operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateNode creates a new node
 */
export function CreateNode(mapID: string, req: $models.CreateNodeRequest): $CancellablePromise<$models.NodeResponse> {
    return $Call.ByID(738378372, mapID, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteNode deletes a node
 */
export function DeleteNode(nodeID: string): $CancellablePromise<void> {
    return $Call.ByID(3045058951, nodeID);
}

/**
 * ExecutableNodes retrieves executable nodes
 */
export function ExecutableNodes(mapID: string, nodeID: string): $CancellablePromise<$models.ExecutableNodesResponse> {
    return $Call.ByID(113249177, mapID, nodeID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListNodes retrieves all nodes in a map
 */
export function ListNodes(mapID: string): $CancellablePromise<$models.NodeResponse[]> {
    return $Call.ByID(1425745849, mapID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UpdateNode updates a node
 */
export function UpdateNode(nodeID: string, req: $models.UpdateNodeRequest): $CancellablePromise<$models.NodeResponse> {
    return $Call.ByID(1431180373, nodeID, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.NodeResponse.createFrom;
const $$createType1 = $models.ExecutableNodesResponse.createFrom;
const $$createType2 = $Create.Array($$createType0);
