// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThinkingBinding exposes AI thinking operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Conclusion initiates the conclusion process (streaming)
 */
export function Conclusion(req: $models.ConclusionRequest): $CancellablePromise<void> {
    return $Call.ByID(2330633355, req);
}

/**
 * Decomposition initiates the decomposition process (streaming)
 */
export function Decomposition(req: $models.DecompositionRequest): $CancellablePromise<void> {
    return $Call.ByID(667314639, req);
}

/**
 * Repeat re-runs the thinking process
 */
export function Repeat(nodeID: string): $CancellablePromise<void> {
    return $Call.ByID(1634635859, nodeID);
}

/**
 * Understanding initiates the understanding process (streaming)
 */
export function Understanding(req: $models.UnderstandingRequest): $CancellablePromise<void> {
    return $Call.ByID(3784669762, req);
}
