// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Conclusion {
    /**
     * 对话ID
     */
    "conversationID": string;

    /**
     * 最后一条消息ID
     */
    "lastMessageID": string;

    /**
     * 最终结论
     */
    "content": string;

    /** Creates a new Conclusion instance. */
    constructor($$source: Partial<Conclusion> = {}) {
        if (!("conversationID" in $$source)) {
            this["conversationID"] = "";
        }
        if (!("lastMessageID" in $$source)) {
            this["lastMessageID"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conclusion instance from a string or object.
     */
    static createFrom($$source: any = {}): Conclusion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conclusion($$parsedSource as Partial<Conclusion>);
    }
}

export class Decomposition {
    /**
     * 是否分解
     */
    "isDecomposed": boolean;

    /**
     * 对话ID
     */
    "conversationID": string;

    /**
     * 最后一条消息ID
     */
    "lastMessageID": string;

    /** Creates a new Decomposition instance. */
    constructor($$source: Partial<Decomposition> = {}) {
        if (!("isDecomposed" in $$source)) {
            this["isDecomposed"] = false;
        }
        if (!("conversationID" in $$source)) {
            this["conversationID"] = "";
        }
        if (!("lastMessageID" in $$source)) {
            this["lastMessageID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Decomposition instance from a string or object.
     */
    static createFrom($$source: any = {}): Decomposition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Decomposition($$parsedSource as Partial<Decomposition>);
    }
}

/**
 * DependentContext 依赖上下文
 */
export class DependentContext {
    /**
     * 祖先节点
     */
    "ancestor"?: NodeContext[];

    /**
     * 前置兄弟节点
     */
    "prevSibling"?: NodeContext[];

    /**
     * 子节点
     */
    "children"?: NodeContext[];

    /** Creates a new DependentContext instance. */
    constructor($$source: Partial<DependentContext> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependentContext instance from a string or object.
     */
    static createFrom($$source: any = {}): DependentContext {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ancestor" in $$parsedSource) {
            $$parsedSource["ancestor"] = $$createField0_0($$parsedSource["ancestor"]);
        }
        if ("prevSibling" in $$parsedSource) {
            $$parsedSource["prevSibling"] = $$createField1_0($$parsedSource["prevSibling"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField2_0($$parsedSource["children"]);
        }
        return new DependentContext($$parsedSource as Partial<DependentContext>);
    }
}

/**
 * NodeContext 节点上下文
 */
export class NodeContext {
    "question": string;
    "target": string;
    "conclusion": string;
    "abstract": string;
    "status": string;

    /** Creates a new NodeContext instance. */
    constructor($$source: Partial<NodeContext> = {}) {
        if (!("question" in $$source)) {
            this["question"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("conclusion" in $$source)) {
            this["conclusion"] = "";
        }
        if (!("abstract" in $$source)) {
            this["abstract"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeContext instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeContext($$parsedSource as Partial<NodeContext>);
    }
}

/**
 * Position 节点位置信息
 */
export class Position {
    "x": number;
    "y": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

// Private type creation functions
const $$createType0 = NodeContext.createFrom;
const $$createType1 = $Create.Array($$createType0);
